### ISSUE TITLE
Could not find any subfolders with Terragrunt configuration files

### ISSUE THREAD

**Issue by Genaker** [antonbabenko/modules.tf-demo#2]
![image](https://user-images.githubusercontent.com/9213670/68536781-2517db00-030d-11ea-92d4-a47e1b368b3c.png)
When running:
terragrunt apply-all
```
[terragrunt] [/home/genaker/Downloads/Cloud-craft-former/cloud-craft_former/us-west-1] 2019/11/09 16:20:16 Running command: terraform --version
[terragrunt] 2019/11/09 16:20:16 Could not find any subfolders with Terragrunt configuration files
[terragrunt] 2019/11/09 16:20:16 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by Genaker** [comment]
![image](https://user-images.githubusercontent.com/9213670/68536844-4af1af80-030e-11ea-98b9-be0bbcafb63c.png)


When running 

terragrunt plan
```
[terragrunt] [/home/genaker/Downloads/Cloud-craft-former/cloud-craft_former/us-west-1] 2019/11/09 16:28:14 Running command: terraform --version
[terragrunt] 2019/11/09 16:28:14 Reading Terragrunt config file at /home/genaker/Downloads/Cloud-craft-former/cloud-craft_former/us-west-1/terraform.tfvars
[terragrunt] 2019/11/09 16:28:14 Error reading file at path /home/genaker/Downloads/Cloud-craft-former/cloud-craft_former/us-west-1/terraform.tfvars: open /home/genaker/Downloads/Cloud-craft-former/cloud-craft_former/us-west-1/terraform.tfvars: no such file or directory
[terragrunt] 2019/11/09 16:28:14 Unable to determine underlying exit code, so Terragrunt will exit with error code 
```

I had this issue before. Adding empty /terraform.tfvars resolving this issue. Can you suggest how to fix it?

**Comment by antonbabenko** [comment]
Please check the content of this repo. Many things has changed since previous release when `terraform.tfvars` was used.

1. There should be no reference to `terraform.tfvars` if you don't have it.
2. There are `terragrunt.hcl` files instead of `terraform.tfvars`.
3. Verify and make sure to use latest version of terragrunt & terraform.

If issue persists, please run `tree .` in root dir to list all directories and files you have.

**Comment by Genaker** [comment]
Yes, the issue was in the Terragrun version. Fixed:

genaker@genaker:~/Downloads/Cloud-craft-former$ sudo wget "https://github.com/gruntwork-io/terragrunt/releases/download/v0.21.5/terragrunt_linux_386"
genaker@genaker:~/Downloads/Cloud-craft-former$ mv terragrunt_linux_386 terragrunt
genaker@genaker:~/Downloads/Cloud-craft-former$ cp terragrunt /bin/
genaker@genaker:~/Downloads/Cloud-craft-former$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
genaker@genaker:~/Downloads/Cloud-craft-former$ sudo chmod +x /bin/terragrunt
genaker@genaker:~/Downloads/Cloud-craft-former$ terragrunt -v
terragrunt version v0.21.5
