### ISSUE TITLE
How would i deploy to a second region?

### ISSUE THREAD

**Issue by sdot257** [antonbabenko/modules.tf-demo#5]
Seeing that `common/main_providers.tf` references `eu-west-1`, if I create another folder on the same level as `eu-west-1`, would i need to make another `common/main_providers.tf` to reflect the second region?

**Comment by antonbabenko** [comment]
Yes, you need to specify region in provider configuration by copying `common/main_providers.tf` as you describe and update a path to the file inside `after_hook "copy_common_main_providers"` in `<new-region>/terragrunt.hcl`.

Please do not hesitate to ask other questions as you move along.
